# INI 工具
[server] 
AppMode = debug
HttpPort = :3000

; [database]
; Db = mysql
; DbHost = localhost
; DbPort = 3306
; DbUser = svb
; DbPassWord = svb2861
; DbName = base

[database]
Db = mysql
DbHost = 47.113.149.62
DbPort = 3306
DbUser = svb
DbPassWord = svb2861
DbName = base

[security]

aes_secret_key = f2f7cca6797d36921e286a82301e7a51

[reminder]
# 定时检查间隔（分钟）
check_interval = 1

[email]
SenderEmail = "cspona@qq.com"
SmtpServer  = "smtp.qq.com"
SmtpPort    = "465"
SmtpPass    = "burimslxnjkudagb"

[upload]
Dir =
